### ISSUE TITLE
# model‘s huggingface url is updated

### ISSUE THREAD

**Issue by weny911** [Meituan-AutoML/Lenna#3]
有很多bug，作者并为在README中讲清楚

**Comment by weifei7** [comment]
你好，请问你遇到了什么错误呢？请贴出来一起讨论，而不是直接给无理由的指责，谢谢

**Comment by weifei7** [comment]
@liwenyang-911

**Comment by weifei7** [comment]
sorry 看到您在另一个issue中的提问了，抱歉没有及时回复，麻烦在新的huggingface链接中重新下载一下模型，之前的链接有部分模型上传失败了，抱歉
