### ISSUE TITLE
关于论文中实验结果的疑问

### ISSUE THREAD

**Issue by jiangtann** [Meituan-AutoML/Lenna#6]
论文Table 5 E1中，只用REC数据训练的时候，refcoco的点数是31.78。但使用O365,GoldG预训练好的，没在REC上finetune过的GroundingDino，refcoco的点数都是50.41。Table 5所使用的llava和Groundingdino应该都是预训练好的吧，不是从头训练的。那意思是只用REC去finetune lenna，会造成性能从50.41下降成31.78吗？

![image](https://github.com/Meituan-AutoML/Lenna/assets/39088437/19c7db04-1f8d-4c29-851c-a124284d84ba)
<img width="1062" alt="image" src="https://github.com/Meituan-AutoML/Lenna/assets/39088437/f53cbbfa-64e6-418c-9ad7-a6b87adecb1e">

**Comment by weifei7** [comment]
@jiangtann 感谢你的细心反馈！我check了下实验记录，这组实验是只用OD和VQA数据来训练的，没有用REC数据。我们会在下一个版本更正这个表格的错误，也会补充仅REC数据训练的指标，感谢关注～

**Comment by jiangtann** [comment]
因为论文中提到了4个数据集，想问下Table 5中的实验数据中，是都用了Reasoning detection data吗？是因为这个数据集对refcoco的点数影响很小，所以没有提到吗。

**Comment by weifei7** [comment]
@jiangtann 是的，Table5都用了Reason数据，E4即为主表中的Lenna-7B模型。Reasoning detection data来源是ReasonSeg数据集（from LISA），训练集只有二百多张图像，对REC任务影响较小，它主要影响模型的reason能力 见Table 3的对比～
