### ISSUE TITLE
Request for Access to ReasonDet Dataset

### ISSUE THREAD

**Issue by codefanw** [Meituan-AutoML/Lenna#7]
Thanks for your impressive work! Is the ReasonDet dataset mentioned in your paper available for public use?

**Comment by weifei7** [comment]
@codefanw Sure! You should firstly download the images from [LISA-reasonseg dataset](https://github.com/dvlab-research/LISA?tab=readme-ov-file#dataset). The coco format detection annotations are there: 
[reasondet_annotations.zip](https://github.com/Meituan-AutoML/Lenna/files/13915930/reasondet_annotations.zip)

**Comment by codefanw** [comment]
Thanks for generously sharing!

**Comment by codefanw** [comment]
> @codefanw Sure! You should firstly download the images from [LISA-reasonseg dataset](https://github.com/dvlab-research/LISA?tab=readme-ov-file#dataset). The coco format detection annotations are there: [reasondet_annotations.zip](https://github.com/Meituan-AutoML/Lenna/files/13915930/reasondet_annotations.zip)

Thanks for generously sharing!
